on:
  workflow_call:
    inputs:
      project:
        type: string
        description: dbt project
        required: true
      environment:
        type: string
        description: dbt target
        required: true

env:
  MY_ENV_VAR: ${{ vars.MY_ENV_VAR }}

jobs:
  call-only:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Echo inputs
        run: |
          echo "Project: ${{ inputs.project }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "MY_ENV_VAR: ${{ env.MY_ENV_VAR }}"
          echo "MY_SECRET_PASSWORD: ${{ secrets.MY_SECRET_PASSWORD }}"
