

on:
  workflow_dispatch:
    inputs:
      project:
        type: choice
        description: dbt project
        required: true
        options:
          - "biz_product_rdb"
      environment:
        type: choice
        description: target environment
        required: true
        options:
          - "dev"
          - "prd"


jobs:
  manual1:
    uses: ./.github/workflows/call-only.yml
    secrets: inherit
    with:
      project:  ${{ github.event.inputs.project }}
      environment:  ${{ github.event.inputs.environment }}
