name: Scheduled build

on:
  schedule:
    - cron: '0 0 1 1 *'

jobs:
  deploy_dev:
    secrets: inherit
    uses: ./.github/workflows/call-only.yml
    with:
      project: "biz_product_rdb"
      environment: "dev"
